//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValleyDreamsIndia
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int Id { get; set; }
        public string NomineeName { get; set; }
        public string NomineeRelation { get; set; }
        public string BankName { get; set; }
        public string AccountHolderName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string PANNumber { get; set; }
        public string TransactionPassword { get; set; }
        public Nullable<int> UsersDetailsId { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
