//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValleyDreamsIndia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionDetail
    {
        public int Id { get; set; }
        public Nullable<int> ContribNumber { get; set; }
        public Nullable<System.DateTime> ContribDate { get; set; }
        public Nullable<int> ContribAmount { get; set; }
        public Nullable<int> NextContribNumber { get; set; }
        public Nullable<System.DateTime> NextContribDate { get; set; }
        public Nullable<int> RemainingContrib { get; set; }
        public Nullable<int> UserDetailsId { get; set; }
        public Nullable<int> SponsoredId { get; set; }
        public string PayedBy { get; set; }
        public Nullable<int> IsCompleted { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
