//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValleyDreamsIndia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Mobile { get; set; }
        public string ProfilePic { get; set; }
        public string PlacementSide { get; set; }
        public string NomineeName { get; set; }
        public string NomineeRelation { get; set; }
        public Nullable<int> UsersDetailsId { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> SponsoredId { get; set; }
    
        public virtual UsersDetail UsersDetail { get; set; }
    }
}
