//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValleyDreamsIndia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ValleyDreamsIndiaDBEntities : DbContext
    {
        public ValleyDreamsIndiaDBEntities()
            : base("name=ValleyDreamsIndiaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankDetail> BankDetails { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<ContributionDetail> ContributionDetails { get; set; }
        public virtual DbSet<RenewalPinDetail> RenewalPinDetails { get; set; }
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<UsersDetail> UsersDetails { get; set; }
    
        public virtual ObjectResult<CountPlacementSideFunc_Result> CountPlacementSideFunc(Nullable<int> uSERSDETAILSID)
        {
            var uSERSDETAILSIDParameter = uSERSDETAILSID.HasValue ?
                new ObjectParameter("USERSDETAILSID", uSERSDETAILSID) :
                new ObjectParameter("USERSDETAILSID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountPlacementSideFunc_Result>("CountPlacementSideFunc", uSERSDETAILSIDParameter);
        }
    }
}
